apiVersion: apps/v1
kind: Deployment
metadata:
  name: springpetclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springpetclinic
  template:
    metadata:
      labels:
        app: springpetclinic
    spec:
      containers:
      - name: springpetclinic
        image: tounakti261/springpetclinic:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springpetclinic-service
spec:
  type: NodePort
  selector:
    app: springpetclinic
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
